"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import Navbar from "@/components/Navbar";
import EventCard from "@/components/EventCard";

export default function Home() {
  const [query, setQuery] = useState("");
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [loadingHistory, setLoadingHistory] = useState(false);
  const [error, setError] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchHistory = async (pageNum = 1) => {
    setLoadingHistory(true);
    try {
      const res = await axios.get(`/api/ai?page=${pageNum}&limit=5`);
      setTotalPages(res.data?.pagination?.pages || 1);

      if (pageNum === 1) {
        setHistory(res.data.data);
      } else {
        setHistory((prev) => [...prev, ...res.data.data]);
      }
    } catch (err) {
      console.error(err);
      setError("Could not load previous searches. Please try again.");
    } finally {
      setLoadingHistory(false);
    }
  };

  useEffect(() => {
    fetchHistory(1);
  }, []);

  const handleSubmit = async () => {
    if (!query.trim()) return;

    setLoading(true);
    setError("");
    try {
      const res = await axios.post("/api/ai", {
        userInput: query,
      });

      setResult(res.data.data);
      setQuery("");
      setPage(1);
      fetchHistory(1);
    } catch (err) {
      console.error(err);
      const apiMessage = err?.response?.data?.error;
      setError(apiMessage || "AI request failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const hasMore = page < totalPages;

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      <main className="max-w-5xl mx-auto px-4 py-8 sm:py-10">
        <section className="text-center mb-8 sm:mb-10">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">
            AI Event Concierge
          </h1>
          <p className="mt-2 text-gray-600 max-w-2xl mx-auto">
            Describe your corporate offsite and get a structured venue proposal with cost and fit justification.
          </p>
        </section>

        <section className="bg-white border border-gray-200 p-5 sm:p-6 rounded-2xl shadow-sm">
          <label htmlFor="eventQuery" className="block text-sm font-medium text-gray-700 mb-2">
            Event Brief
          </label>

          <textarea
            id="eventQuery"
            rows={4}
            className="w-full border border-gray-300 p-3 rounded-xl focus:ring-2 focus:ring-gray-900 focus:border-gray-900 outline-none resize-none"
            placeholder="e.g. 10 people team offsite in Goa for 2 days under ₹50,000"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              if (error) setError("");
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                if (query.trim() && !loading) {
                  handleSubmit();
                }
              }
            }}
          />

          <button
            onClick={handleSubmit}
            disabled={loading || !query.trim()}
            className="mt-4 w-full bg-gray-900 text-white py-3 rounded-xl hover:bg-gray-800 disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {loading ? (
              <>
                <span className="h-4 w-4 rounded-full border-2 border-white/50 border-t-white animate-spin" />
                AI is planning...
              </>
            ) : (
              "Generate Proposal"
            )}
          </button>

          {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
        </section>

        {result && (
          <section className="mt-10">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl sm:text-2xl font-semibold text-gray-900">Current Proposal</h2>
              <span className="text-xs sm:text-sm text-gray-500">Generated by AI</span>
            </div>
            <EventCard item={result} highlightMode />
          </section>
        )}

        <section className="mt-14">
          <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">Previous Searches</h2>

          {history.length === 0 && !loadingHistory ? (
            <div className="bg-white border border-dashed border-gray-300 rounded-2xl p-8 text-center text-gray-500">
              Your search history will appear here.
            </div>
          ) : (
            <div className="grid gap-4">
              {history.map((item) => (
                <EventCard key={item._id} item={item} />
              ))}
            </div>
          )}

          {loadingHistory && (
            <p className="mt-4 text-sm text-gray-500">Loading previous searches...</p>
          )}

          {hasMore && (
            <button
              onClick={() => {
                const nextPage = page + 1;
                setPage(nextPage);
                fetchHistory(nextPage);
              }}
              disabled={loadingHistory}
              className="mt-6 w-full bg-gray-900 text-white py-3 rounded-xl hover:bg-gray-800 disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {loadingHistory ? "Loading..." : "Load More"}
            </button>
          )}
        </section>
      </main>
    </div>
  );
}